"""Official Agent-to-Agent (A2A) Protocol Server.

Powered by Google ADK to expose the Research Assistant Agent
as a compliant A2A microservice over JSON-RPC 2.0 and /.well-known/agent-card.json.
"""

import sys

import uvicorn
from google.adk.a2a.utils.agent_to_a2a import to_a2a
from starlette.requests import Request
from starlette.responses import JSONResponse

from a2a_server.agent.agent import root_agent
from app.core.config import settings
from app.core.logger import get_logger

logger = get_logger("research_agent.a2a_server")

# Official A2A Starlette application generated by Google ADK
# Exposes JSON-RPC 2.0 at / and the official Agent Card at /.well-known/agent-card.json
a2a_app = to_a2a(root_agent, port=8082)


async def health_endpoint(request: Request) -> JSONResponse:
    """Readiness probe for A2A intelligence server container."""
    return JSONResponse(
        {
            "status": "healthy",
            "service": "a2a_server",
            "model": settings.gemini_model,
            "version": "1.0.0",
        }
    )


# Optional liveness check for container health monitoring
a2a_app.add_route("/health", health_endpoint, methods=["GET"])


if __name__ == "__main__":
    port = 8082
    if "--port" in sys.argv:
        try:
            port = int(sys.argv[sys.argv.index("--port") + 1])
        except (IndexError, ValueError):
            pass

    logger.info(f"Starting official A2A Core Server on port {port}")
    uvicorn.run(a2a_app, host="0.0.0.0", port=port)
