"""Official Agent-to-Agent (A2A) Protocol Server.

Powered by Google ADK and a2a-sdk to expose the Research Assistant Agent
as the core intelligence service over standard A2A JSON-RPC 2.0 and REST.
"""

import asyncio
import sys

import uvicorn
from google.adk.a2a.utils.agent_to_a2a import to_a2a
from starlette.requests import Request
from starlette.responses import JSONResponse

from a2a_server.agent.agent import ReActAgentRunner, root_agent
from a2a_server.core.advanced_retrieval import ChainedRAGPipeline
from app.core.config import settings
from app.core.logger import get_logger
from app.schema.structured_output import UserProfileContext

logger = get_logger("research_agent.a2a_server")

# Base Starlette app generated by Google ADK with official A2A protocol (JSON-RPC)
a2a_app = to_a2a(root_agent, port=8082)


# ============================================================================
# REST Microservice Endpoints for Decoupled Web Backend Communication
# ============================================================================


async def health_endpoint(request: Request) -> JSONResponse:
    """Readiness probe for A2A intelligence server container."""
    return JSONResponse(
        {
            "status": "healthy",
            "service": "a2a_server",
            "model": settings.gemini_model,
            "version": "1.0.0",
        }
    )


async def chat_endpoint(request: Request) -> JSONResponse:
    """Execute the autonomous ReAct reasoning and action cycle."""
    try:
        payload = await request.json()
    except Exception:
        return JSONResponse({"error": "Invalid JSON body"}, status_code=400)

    query = payload.get("message") or payload.get("query")
    if not query:
        return JSONResponse({"error": "'message' or 'query' is required"}, status_code=422)

    session_id = payload.get("session_id")
    max_iterations = int(payload.get("max_iterations", 5))
    history = payload.get("history")

    raw_profile = payload.get("user_profile")
    user_profile = None
    if raw_profile and isinstance(raw_profile, dict):
        user_profile = UserProfileContext(**raw_profile)

    runner = ReActAgentRunner()
    final_answer, trace, structured = await runner.run(
        query=query,
        session_id=session_id,
        max_iterations=max_iterations,
        user_profile=user_profile,
        history=history,
    )

    # Format step tool traces for remote consumption
    tool_traces = []
    for step in trace.steps:
        if step.thought:
            tool_traces.append(
                {
                    "type": "thought",
                    "name": f"Step {step.step_number}",
                    "response": step.thought,
                }
            )
        if step.action:
            tool_traces.append(
                {
                    "type": "function_call",
                    "name": step.action,
                    "args": step.action_input,
                    "response": step.observation,
                }
            )

    return JSONResponse(
        {
            "response": final_answer,
            "session_id": session_id,
            "tool_traces": tool_traces,
            "trace": trace.model_dump(),
            "structured_synthesis": structured.model_dump() if structured else None,
        }
    )


async def query_endpoint(request: Request) -> JSONResponse:
    """Execute direct Chained RAG pipeline with HyDE and Multi-Query expansion."""
    try:
        payload = await request.json()
    except Exception:
        return JSONResponse({"error": "Invalid JSON body"}, status_code=400)

    query = payload.get("query") or payload.get("message")
    if not query:
        return JSONResponse({"error": "'query' or 'message' is required"}, status_code=422)

    top_k = int(payload.get("top_k", 5))
    use_hyde = bool(payload.get("use_hyde", True))
    use_multiquery = bool(payload.get("use_multiquery", True))
    history = payload.get("history")

    raw_profile = payload.get("user_profile")
    user_profile = None
    if raw_profile and isinstance(raw_profile, dict):
        user_profile = UserProfileContext(**raw_profile)

    pipeline = ChainedRAGPipeline()
    result = await asyncio.to_thread(
        pipeline.run,
        query=query,
        top_k=top_k,
        use_hyde=use_hyde,
        use_multiquery=use_multiquery,
        user_profile=user_profile,
        history=history,
    )

    return JSONResponse(result.model_dump())


async def info_endpoint(request: Request) -> JSONResponse:
    """Return tool catalog and capabilities metadata."""
    runner = ReActAgentRunner()
    tool_names = list(runner.tool_registry.keys())
    tools_manifest = [
        {
            "name": name,
            "description": (getattr(func, "__doc__", "") or "").split("\n\n")[0].strip(),
        }
        for name, func in runner.tool_registry.items()
    ]
    return JSONResponse(
        {
            "name": "research_agent",
            "framework": "ReAct (Reasoning + Action + Observation)",
            "model": settings.gemini_model,
            "tools": tool_names,
            "tools_manifest": tools_manifest,
        }
    )


# Mount REST microservice routes onto the A2A ASGI app
a2a_app.add_route("/health", health_endpoint, methods=["GET"])
a2a_app.add_route("/api/v1/chat", chat_endpoint, methods=["POST"])
a2a_app.add_route("/api/v1/query", query_endpoint, methods=["POST"])
a2a_app.add_route("/api/v1/info", info_endpoint, methods=["GET"])


if __name__ == "__main__":
    port = 8082
    if "--port" in sys.argv:
        try:
            port = int(sys.argv[sys.argv.index("--port") + 1])
        except (IndexError, ValueError):
            pass

    logger.info(f"Starting official A2A Core Server on port {port}")
    uvicorn.run(a2a_app, host="0.0.0.0", port=port)
